apiVersion: cloud-build-notifiers/v1
kind: SlackNotifier
metadata:
  name: slack-notifier
spec:
  notification:
    filter: build.status in [Build.Status.FAILURE, Build.Status.TIMEOUT]
    delivery:
      webhookUrl:
        secretRef: webhook-url
  secrets:
  - name: webhook-url
    value: projects/600888475582/secrets/slack-incomming-webhook-dev-notification-error/versions/latest
