apiVersion: cloud-build-notifiers/v1
kind: SlackNotifier
metadata:
  name: slack-notifier
spec:
  notification:
    filter: build.status == Build.Status.SUCCESS
    delivery:
      webhookUrl:
        secretRef: webhook-url
  secrets:
  - name: webhook-url
    value: projects/224339710364/secrets/slack-incomming-webhook-dev-notification-info/versions/latest
